import type { Metadata } from 'next'
import { Oswald, Roboto_Mono } from 'next/font/google'
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import ResponsiveAppBar from '@/src/features/layout/ResponsiveAppbar';
export const oswald = Oswald({
  subsets: ['latin'],
  display: 'swap',
})
export const roboto = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const routes =[
  {path: '/', label:'Accueil'},
  {path:'/about',label:'À Propos'},
  {path:'/prestations',label:'Prestations'},
  {path:'/contact',label:'Contact'},
]
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ResponsiveAppBar routes={routes} />
      <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </body>
    </html>
  )
}
