import type { Metadata } from 'next'
import { Oswald, Roboto_Mono } from 'next/font/google'
import { clsx } from 'clsx';
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import ResponsiveAppBar from '@/src/features/layout/ResponsiveAppbar';
import ScrollTopTop from '@/src/features/layout/ScrollToTop';
export const oswald = Oswald({
  subsets: ['latin'],
  display: 'swap',
})
export const roboto = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const routes = [
  { path: '/', label: 'La Naturopathie' },
  { path: '/about', label: 'Qui suis-je ?' },
  { path: '/prestations', label: 'Mes accompagnements' },
  { path: '/ateliers', label: 'Ateliers' },
  { path: '/contact', label: 'Contact' },
]
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(roboto.className, "App")}>
        <ResponsiveAppBar routes={routes} />
        <ScrollTopTop />
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>

      </body>
    </html>
  )
}
